FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o writer ./cmd/writer

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/writer .

EXPOSE 8080
CMD ["./writer"] 