FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o reader ./cmd/reader

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/reader .

EXPOSE 8080
CMD ["./reader"] 